---
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.13
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=HST
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - E:\Docker\sonarr\data:/config
      - F:\Plex Media\TV Series:/tv #optional
      #- /path/to/downloadclient-downloads:/downloads #optional
    ports:
      - 8989:8989
