---
version: "2.1"
services:
  overseerr:
    image: lscr.io/linuxserver/overseerr:2021.12.12
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=HST
    volumes:
      - E:\Docker\overseerr\config:/config
    ports:
      - 5055:5055
    restart: unless-stopped
