server=1
txindex=1
listen=1
daemon=0
rpcbind=0.0.0.0
rpcallowip=127.0.0.1
rpcuser=bitcoin
rpcpassword=testing
zmqpubrawblock=tcp://0.0.0.0:28332
zmqpubrawtx=tcp://0.0.0.0:28333
zmqpubhashblock=tcp://0.0.0.0:28334
zmqpubsequence=tcp://0.0.0.0:28335
blockfilterindex=1
peerblockfilters=1
