---
services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:2025.9.3
    container_name: homeassistant
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=HST
    volumes:
      - /docker/homeassistant/data:/config
    ports:
      - 8123:8123 #optional
    #devices:
      #- /path/to/device:/path/to/device #optional
    restart: unless-stopped
