---
services:
radarr:
    image: lscr.io/linuxserver/radarr:5.19.3
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=HST
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - E:\Docker\radarr\data:/config
      - F:\Plex Media\Movies:/movies #optional
      #- /path/to/download-client-downloads:/downloads #optional
    ports:
      - 7878:7878
