services:
  umbrel:
    image: dockurr/umbrel:1.4.0
    container_name: umbrel
    pid: host
    ports:
      - "32770:80"
    volumes:
      - /data/bitcoin:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    stop_grace_period: 1m
