---
services:
  gluetun:
      image: qmcgaw/gluetun:v3.40
      container_name: gluetun
      cap_add:
        - NET_ADMIN
      devices:
        - /dev/net/tun:/dev/net/tun
      ports:
        - 8080:8080 # qbittorrent web interface
        - 6881:6881 # qbittorrent torrent port
        - 9696:9696 # prowlarr
      volumes:
        - /docker/gluetun:/gluetun
      environment:
        - VPN_SERVICE_PROVIDER=ipvanish
        - OPENVPN_USER=waggoner28@gmail.com
        - OPENVPN_PASSWORD=waggoner28@gmail.com
        - SERVER_COUNTRIES=United States
      healthcheck:
        test: ping -c 1 www.google.com || exit 1
        interval: 60s
        timeout: 20s
        retries: 5
      restart: unless-stopped
