---
services:
  deunhealth:
      image: qmcgaw/deunhealth:v0.3.0
      container_name: deunhealth
      network_mode: "none"
      environment:
        - LOG_LEVEL=info
        - HEALTH_SERVER_ADDRESS=127.0.0.1:9999
        - TZ=HST
      restart: always
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
