---

services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:v3.4.1
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=HST
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped 
